language: node_js
node_js:
  - "4"
  - "5"
before_install:
  - npm install -g gulp jspm@0.17.0-beta.7 tsd karma
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gulp build:compile
  - gulp e2e:linux
  